apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: account-service
spec:
  hosts:
  - account-service
  http:
  - route:
    - destination:
        host: account-service
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-service
spec:
  hosts:
  - auth-service
  http:
  - route:
    - destination:
        host: auth-service
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: config
spec:
  hosts:
  - config
  http:
  - route:
    - destination:
        host: config
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway
spec:
  hosts:
  - piggymetrics-ops.mapsic.cn
  gateways:
  - piggymetrics-gateway
  http:
  - route:
    - destination:
        port:
          number: 4000
        host: gateway
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monitoring
spec:
  hosts:
  - hystrix-ops.mapsic.cn
  gateways:
  - hystrix-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: monitoring
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notification-service
spec:
  hosts:
  - notification-service
  http:
  - route:
    - destination:
        host: notification-service
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: registry
spec:
  hosts:
  - registry-ops.mapsic.cn
  gateways:
  - registry-gateway
  http:
  - route:
    - destination:
        host: registry
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: statistics-service
spec:
  hosts:
  - statistics-service
  http:
  - route:
    - destination:
        host: statistics-service
        subset: v1
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: turbine-stream-service
spec:
  hosts:
  - turbine-stream-service
  http:
  - route:
    - destination:
        host: turbine-stream-service
        subset: v1
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-mongodb
spec:
  hosts:
  - auth-mongodb
  http:
  - route:
    - destination:
        host: auth-mongodb
        subset: v1
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: account-mongodb
spec:
  hosts:
  - account-mongodb
  http:
  - route:
    - destination:
        host: account-mongodb
        subset: v1
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notification-mongodb
spec:
  hosts:
  - notification-mongodb
  http:
  - route:
    - destination:
        host: notification-mongodb
        subset: v1
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: statistics-mongodb
spec:
  hosts:
  - statistics-mongodb
  http:
  - route:
    - destination:
        host: statistics-mongodb
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rabbitmq-ui
spec:
  hosts:
  - rabbitmq-ops.mapsic.cn
  gateways:
  - rabbitmq-gateway
  http:
  - route:
    - destination:
        host: rabbitmq
        subset: v1
        port: 
          number: 15672      
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rabbitmq
spec:
  hosts:
  - rabbitmq
  http:
  - route:
    - destination:
        host: rabbitmq
        subset: v1
